### ISSUE TITLE
Splitting up sudo_script and faf_script.

### ISSUE THREAD

**Issue by amrsoll** [tatsujb/installFAFscript#12]
For the sake of convenience I understand why there are sub scripts in the form some long string in `faf.sh`, but I thought it might help to separate them into `sudo_script.sh` and `faf_script.sh`, so as to eventually `curl` download and run these extra scripts from the main one?

**Comment by tatsujb** [comment]
yeah. great idea! I'm learning as I go with this. As I am looking for contributors, you are welcome to ask and I will make you one and you'll be able to push any changes you want.

**Comment by tatsujb** [comment]
@amrsoll I'm looking into implement this but I want to know if you have any ideas regarding where I could curl from?

I want to host on github, ideally as a branch of this project/or another project but to be curlable, there has to be a release right?

**Comment by amrsoll** [comment]
You can curl or wget the scripts from github with this url formatting (considering the faf.sh file) using the "raw view" of github

With a release :

https://raw.githubusercontent.com/tatsujb/installFAFscript/2.3/faf.sh

In a branch :

https://raw.githubusercontent.com/tatsujb/installFAFscript/master/faf.sh \
https://raw.githubusercontent.com/tatsujb/installFAFscript/feat/de-spaghettify/faf.sh

**Comment by amrsoll** [comment]
but I do believe it is easiest to download the files and ask the terminals to just exec the scripts
```bash
if ![ -f sudo_script.sh ]
then
    wget $url/sudo_script.sh
fi
exec $emulator -e sudo_script.sh
```

**Comment by amrsoll** [comment]
The precise commit isn't reference because we haven't managed it correctly, but it is done and stable now.
