### ISSUE TITLE
jdk10 archive site links have changed

### ISSUE THREAD

**Issue by foodlfg** [tatsujb/installFAFscript#7]
the jdk10 archive site links has changed.

the old one:
`wget https://download.java.net/java/GA/jdk10/10.0.2/19aef61b38124481863b1413dce1855f/13/openjdk-10.0.2_linux-x64_bin.tar.gz`

the new one should be:
`wget https://download.oracle.com/java/GA/jdk10/10.0.2/19aef61b38124481863b1413dce1855f/13/openjdk-10.0.2_linux-x64_bin.tar.gz`

Thanks!

**Comment by tatsujb** [comment]
both still work though?

**Comment by foodlfg** [comment]
i didn't notice that. 
the first one works too even tho they have changed the link on the site. oO
