### ISSUE TITLE
Can't select dotfolders with picker

### ISSUE THREAD

**Issue by douglasg14b** [tatsujb/installFAFscript#8]
My steam install and games are under `~/.steam`. The file picker that asks to select the grandparent folder doesn't show dotfolder and it also has no method for typing in a path.

The GTK file selection dialog doesn't seem to have this capability? On KDE DIs you can probably use the KDE file selection dialog.

I'm on Kubuntu 18.10

**Comment by tatsujb** [comment]
Ctrl-H reveals hidden folders and files. this works in every browser, even a file finder.

hope this helps. :)

**Comment by douglasg14b** [comment]
Also found that Ctrl+L lets you type in a path.

**Comment by douglasg14b** [comment]
@tatsujb 

Side question. When it says select the grandparent folder. That means 2 directories up from the folder that contains `steamapps/common/...`? If not, that language is a bit ambiguous if it actually means "Select the folder that contains `steamapps/common/...`?

**Comment by tatsujb** [comment]
yeah it's the second. you can get it by trial and error too. the window will keep reappearing until it actually finds that folder hierarchy under what you gave it. 

and yes Ctrl+L allows you to type in paths. useful for samba connections in particular.
